# Generated by Django 6.0.7 on 2026-07-16 15:25

import django.core.validators
import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, help_text='Optional image, sound, or video shown when this question starts.', upload_to='question_media/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp3', 'wav', 'ogg', 'm4a', 'mp4', 'webm', 'mov', 'ogv']), quizzes.models.validate_media_file_size]),
        ),
    ]
