# Generated by Django 6.0.7 on 2026-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='auto_close_when_all_answered',
            field=models.BooleanField(default=False, help_text='Close a question as soon as every joined player has answered, without waiting for the time limit.'),
        ),
    ]
