# Generated by Django 6.0.7 on 2026-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_auto_close_when_all_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='theme',
            field=models.CharField(choices=[('basic', 'Basic'), ('colored', 'Colored'), ('dark', 'Dark')], default='basic', help_text='Visual style used on the host and player screens while playing.', max_length=20),
        ),
    ]
