# Generated by Django 6.0.7 on 2026-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
